version: '3.8'

services:
  app:
    container_name: django_app30
    build:
      context: .
    ports:
      - 8000:8000
    volumes: 
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: pg_db30
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:                  # map persistent data from container (/var/lib/postgresql/data) to "pgdata" folder on the current directory.
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - 5436:5432
    